version: 0.1.0.{build}

os: Visual Studio 2019

configuration:
  - Debug
  - Release

init:
  - git config --global core.autocrlf true

before_build:
  - nuget restore src\MethodCheck.sln

build:
  parallel: true
  project: src\MethodCheck.sln
  verbosity: minimal
